http:
  image: tukiyo3/alpine-nginx-php7
  restart: always
  ports:
   - "80:80"
  volumes:
   - ./www/:/var/www/localhost/htdocs/:ro

   - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
   - ./conf/php-fpm7.conf:/etc/php7/php-fpm.d/www.conf:ro
   - ./conf/php.ini:/etc/php7/conf.d/php.ini:ro

   #- ./cron/:/var/spool/cron/crontabs/
  command: sh -c "cd /usr/sbin; nginx; php-fpm7; crond -f -l 2"
